### ISSUE TITLE
Please convert bbPress dashicons to SVG

### ISSUE THREAD

**Issue by ntwb** [ryelle/WordPress#15]
Following up from #14 as I see bbPress dashicons were not converted
![screen shot 2016-11-03 at 10 14 49 am](https://cloud.githubusercontent.com/assets/1016458/20025870/1fb79516-a347-11e6-85c9-f0cf5f85d961.png)

bbPress' plan is to no longer "hide" these icons, they were originally not published on https://developer.wordpress.org/resource/dashicons/ so they'd be available exclusively to bbPress.

The current bbPress dashicons: https://codex.bbpress.org/official-logos-and-icons/
• bbPress Logo: `content: "\f477";` – `class="dashicons dashicons-bbpress-logo"`
• Forums/Hive: `content: "\f449";` – `class="dashicons dashicons-bbpress-forum"`
• Topics/Honey: `content: "\f450";` – `class="dashicons dashicons-bbpress-topic"`
• Replies/Bee: `content: "\f451";` – `class="dashicons dashicons-bbpress-reply"`

** The bbPress [was converted](https://github.com/ryelle/WordPress/blob/d096b64c09bccc1611e89bb72fa12f1853fa2bcf/src/wp-includes/icons/src/buddicons-bbpress-logo.svg) as this icon has always been public

With love and thanks in advance, the bbPress team ❤️

**Comment by field2** [comment]
OK, will work on it, would love some help from bbpress team on the push for svg though!

**Comment by ryelle** [comment]
Are we still bundling the bbPress icons? We don't need to worry about font conflicts or anything, so I think the bbPress icons should be their own sprite/not in core. Not having one big icon file was part of the SVG push. We can adjust the `wp_icon` function to accept a (relative) URL for 3rd-party sprites, and then any plugin author can use that for their icons. If we've had this discussion already about SVGs, sorry for not remembering :)

(also, I second @field2's comment, if anyone from bbPress wants to help us with the SVG conversion... 😄  )

**Comment by ntwb** [comment]
> Are we still bundling the bbPress icons?

Yes, they are in the current dashicons, they are just "hidden" from public view and not documented or publicly viewable on the dashicons site.

The new w.org support forum redesign also doesn't use them currently, I plan on changing that, primarily the reason they were not used in the original redesign was because the icons were not discoverable, you only knew they existed by word of mouth from someone who knew they did. 😞 

>  I think the bbPress icons should be their own sprite/not in core. 

Both bbPress and BuddyPress projects are official sister projects of WordPress, this was the reason they were included in dashicons in the first place. I don't think this should change personally.

There's a pretty extensive suite of bbPress & BuddyPress plugins and themes out there that have been able to utilise these dashicons (not that I've actually counted how many do) but the extra 11 icons overhead should be negligible shouldn't it?

> Would love some help from bbpress team on the push for svg though!

I myself have little, actually, no skills in the design department but here's what we have:

• bbPress SVG logo: https://plugins.trac.wordpress.org/browser/bbpress/assets/icon.svg
• BuddyPress SVG logo: https://plugins.trac.wordpress.org/browser/buddypress/assets/icon.svg

The bbPress & BuddyPress glyphs & SVGs in @field2's repo: https://github.com/field2/buddicons

I forgot that the original buddicons repo included these, apologies for that, if I had of remembered that I would have included it in my original post 😄 

If there's anything else needed please don't hesitate to ask 🙂

**Comment by field2** [comment]
For now, I've just bundled them into the sprite, but we should definitely build in the extension to the wp_icon function (should it be a new issue?)
