### ISSUE TITLE
Accessible SVG Icon Markup

### ISSUE THREAD

**Issue by grayghostvisuals** [ryelle/WordPress#2]
To be accessible the following markup should be used…

```html
<svg aria-hidden="true">
  <use xlink:href="sprite.svg#my-icon"></use>
</svg>
```
**Hide a decorative icon from screen readers**

```html
<svg role="img">
  <title>Text alternative</title>
  <use xlink:href="sprite.svg#my-icon"></use>
</svg>
```
**Provide accessible text for an icon**

*These samples are tested and verified for VoiceOver+Safari, NVDA+Fx and JAWS16+IE11*

**Comment by ryelle** [comment]
I've updated the code output by `wp_icon` so that if a title is passed in, it displays in the title tag, and if not, it adds the `aria-hidden` attribute. It would be used like this:

```
wp_icon(
    'dashicons-yes',
    array(
        'title' => __( 'A text title for screen readers' )
    )
);
```

**Comment by grayghostvisuals** [comment]
👍
